name: 'medallion_dwh'
version: '1.0.0'
config-version: 2
profile: medallion_dwh

# Carpeta donde están tus modelos SQL
model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]


# Carpeta donde se guardarán los archivos compilados
target-path: "target"

# Esquemas donde se crearán las tablas
models:
  medallion_dwh:
    silver:
      +materialized: table
      +strategy: delete+insert

    gold:
      +materialized: view


