version: 2

sources:
  - name: bronze_crm
    schema: bronze
    database: "{{ env_var('POSTGRES_DB', 'warehouse') }}"
    description: "Bronze layer tables containing raw CRM system data ingested daily"
    tags: ["bronze", "raw_data"]

    tables:
      - name: crm_cust_info
        description: "Customer information from CRM system - raw data layer"
        meta:
          csv_path: "/usr/local/airflow/include/datasets/source_crm/cust_info.csv"
          source_system: "Salesforce CRM"
          update_frequency: "daily_full_refresh"
        tags: ["customers", "daily_load"]

        columns:
          - name: cst_id
            description: "Unique customer identifier (Primary Key)"
            data_type: integer
            meta:
              business_name: "Customer ID"

          - name: cst_key
            description: "Customer business key from source system"
            data_type: varchar
            meta:
              business_name: "Customer Key"

          - name: cst_firstname
            description: "Customer first name"
            data_type: varchar
            meta:
              business_name: "First Name"
              pii: true
              anonymizable: true

          - name: cst_lastname
            description: "Customer last name"
            data_type: varchar
            meta:
              business_name: "Last Name"
              pii: true
              anonymizable: true

          - name: cst_material_status
            description: "Customer marital status (Single, Married, Divorced, etc.)"
            data_type: varchar
            meta:
              business_name: "Marital Status"

          - name: cst_gnr
            description: "Customer gender (M/F/Unknown)"
            data_type: varchar
            meta:
              business_name: "Gender"

          - name: cst_create_date
            description: "Date customer was created"
            data_type: date
            meta:
              business_name: "Creation Date"

        tests:
          - dbt_expectations.expect_table_row_count_to_be_between:
              min_value: 1000
              max_value: 100000
          - dbt_expectations.expect_table_columns_to_match_ordered_list:
              column_list: ["cst_id", "cst_key", "cst_firstname", "cst_lastname", "cst_material_status", "cst_gnr", "cst_create_date"]

      - name: crm_prd_info
        description: "Current and Historical Product Information - raw data layer"
        meta:
          csv_path: "/usr/local/airflow/include/datasets/source_crm/prd_info.csv"
          source_system: "Salesforce CRM"
          update_frequency: "daily_full_refresh"
        tags: ["products", "daily_load"]

        columns:
          - name: prd_id
            description: "Unique product identifier"
            data_type: integer
            meta:
              business_name: "Product ID"

          - name: prd_key
            description: "Product business key from source system"
            data_type: varchar
            meta:
              business_name: "Product Key"

          - name: prd_nm
            description: "Product name"
            data_type: varchar
            meta:
              business_name: "Product Name"

          - name: prd_cost
            description: "Cost of the product"
            data_type: numeric
            meta:
              business_name: "Product Cost"

          - name: prd_line
            description: "Product line/category"
            data_type: varchar
            meta:
              business_name: "Product Line"

          - name: prd_start_dt
            description: "Product start date (available from)"
            data_type: date
            meta:
              business_name: "Start Date"

          - name: prd_end_dt
            description: "Product end date (discontinued or null if active)"
            data_type: date
            meta:
              business_name: "End Date"

        tests:
          - dbt_expectations.expect_table_row_count_to_be_between:
              min_value: 100
              max_value: 100000
          - dbt_expectations.expect_table_columns_to_match_ordered_list:
              column_list: ["prd_id", "prd_key", "prd_nm", "prd_cost", "prd_line", "prd_start_dt", "prd_end_dt"]

    tables:
      - name: crm_sales_details
        description: "Transactional records about sales and orders - raw data layer"
        meta:
          csv_path: "/usr/local/airflow/include/datasets/source_crm/sales_details.csv"
          source_system: "Salesforce CRM"
          update_frequency: "daily_full_refresh"
        tags: ["sales", "orders", "daily_load"]

        columns:
          - name: sls_ord_num
            description: "Order number / transaction ID"
            data_type: integer
            meta:
              business_name: "Order Number"

          - name: sls_prd_key
            description: "Product business key in the order"
            data_type: varchar
            meta:
              business_name: "Product Key"

          - name: sls_cust_id
            description: "Customer ID associated with the order"
            data_type: integer
            meta:
              business_name: "Customer ID"

          - name: sls_order_dt
            description: "Date when the order was placed"
            data_type: date
            meta:
              business_name: "Order Date"

          - name: sls_ship_dt
            description: "Date when the order was shipped"
            data_type: date
            meta:
              business_name: "Ship Date"

          - name: sls_due_dt
            description: "Order due date"
            data_type: date
            meta:
              business_name: "Due Date"

          - name: sls_sales
            description: "Total sales amount for the order"
            data_type: numeric
            meta:
              business_name: "Sales Amount"

          - name: sls_quantity
            description: "Quantity of products in the order"
            data_type: integer
            meta:
              business_name: "Quantity"

          - name: sls_price
            description: "Unit price of the product in the order"
            data_type: numeric
            meta:
              business_name: "Unit Price"

        tests:
          - dbt_expectations.expect_table_row_count_to_be_between:
              min_value: 100
              max_value: 500000
          - dbt_expectations.expect_table_columns_to_match_ordered_list:
              column_list: ["sls_ord_num", "sls_prd_key", "sls_cust_id", "sls_order_dt", "sls_ship_dt", "sls_due_dt", "sls_sales", "sls_quantity", "sls_price"]

  # Bronze layer for ERP data

  - name: bronze_erp
    schema: bronze
    database: "{{ env_var('POSTGRES_DB', 'warehouse') }}"
    description: "Bronze layer tables containing raw ERP system data ingested daily"
    tags: ["bronze", "raw_data", "erp"]

    tables:
      - name: erp_cust_az12
        description: "Extra customer information (Birthdate) - raw data layer"
        meta:
          csv_path: "/usr/local/airflow/include/datasets/source_erp/CUST_AZ12.csv"
          source_system: "ERP"
          update_frequency: "daily_full_refresh"
        tags: ["customers", "daily_load"]

        columns:
          - name: cid
            description: "Customer ID"
            data_type: integer
            meta:
              business_name: "Customer ID"

          - name: bdate
            description: "Customer birthdate"
            data_type: date
            meta:
              business_name: "Birthdate"

          - name: gen
            description: "Customer gender"
            data_type: varchar
            meta:
              business_name: "Gender"

        tests:
          - dbt_expectations.expect_table_row_count_to_be_between:
              arguments:
                min_value: 100
                max_value: 100000
          - dbt_expectations.expect_table_columns_to_match_ordered_list:
              arguments:
                column_list: ["cid", "bdate", "gen"]

      - name: erp_loc_a101
        description: "ERP location data - raw data layer"
        meta:
          csv_path: "/usr/local/airflow/include/datasets/source_erp/LOC_A101.csv"
          source_system: "ERP"
          update_frequency: "daily_full_refresh"
        tags: ["locations", "daily_load"]

        columns:
          - name: cid
            description: "Customer ID"
            data_type: integer
            meta:
              business_name: "Customer ID"

          - name: cntry
            description: "Country code"
            data_type: varchar
            meta:
              business_name: "Country"

        tests:
          - dbt_expectations.expect_table_row_count_to_be_between:
              arguments:
                min_value: 100
                max_value: 100000
          - dbt_expectations.expect_table_columns_to_match_ordered_list:
              arguments:
                column_list: ["cid", "cntry"]

      - name: erp_px_cat_g1v2
        description: "ERP product category data - raw data layer"
        meta:
          csv_path: "/usr/local/airflow/include/datasets/source_erp/PX_CAT_G1V2.csv"
          source_system: "ERP"
          update_frequency: "daily_full_refresh"
        tags: ["products", "categories", "daily_load"]

        columns:
          - name: id
            description: "Product ID"
            data_type: integer
            meta:
              business_name: "Product ID"

          - name: cat
            description: "Product category"
            data_type: varchar
            meta:
              business_name: "Category"

          - name: subcat
            description: "Product sub-category"
            data_type: varchar
            meta:
              business_name: "Subcategory"

          - name: maintenance
            description: "Maintenance flag or info"
            data_type: varchar
            meta:
              business_name: "Maintenance"

        tests:
          - dbt_expectations.expect_table_row_count_to_be_between:
              arguments:
                min_value: 30
                max_value: 50000
          - dbt_expectations.expect_table_columns_to_match_ordered_list:
              arguments:
                column_list: ["id", "cat", "subcat", "maintenance"]
